schoolproject/schoolapp/urls.py
from . import views
from django.urls import path
app_name='schoolapp'

urlpatterns = [

    path('',views.home,name='home'),
    path('login',views.login,name='login'),
    path('register', views.register, name='register'),
    path('button',views.button,name='button'),
    path('form',views.form,name='form'),

]

schoolproject/schoolproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

schoolproject/schoolapp/models.py
from django.db import models

# Create your models here.

schoolproject/schoolapp/views.py
from django.contrib import messages, auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.contrib import messages

# Create your views here.
def home(request):
    return render(request,'index.html')
def login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        if username != password:


            return redirect('/button')

        else:
            messages.info(request,"")
            return redirect('/login')
    return render(request,"login.html")








def register(request):
    if request.method == 'POST':
        password = request.POST['password']
        password1 = request.POST['password1']
        if password == password1:
            return redirect('/login')
        else:

            messages.info(request, "password not matching")





    return render(request,'register.html')


def button(request):



    return render(request, 'button.html')


def form(request):
    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['mail id']
        if username != password:


            messages.info(request, "order confirmed")

        else:
            messages.info(request, "")





    return render(request,'form.html')

schoolproject/templates/button.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a  class="btn btn-primary" href="{% url 'schoolapp:form' %}">form</a>
</body>
</html>

schoolproject/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>form</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">


	<style>
		.box {
			background-color: black;
			height: 100vh;
			display: flex;
			align-items: center;
			justify-content: center;
		}
		p {
			font-size: 17px;
			align-items: center;
		}
		.box a {
			display: inline-block;
			background-color: #fff;
			padding: 15px;
			border-radius: 3px;
		}
		.modal {
			align-items: center;
			display: flex;
			justify-content: center;
			position: absolute;
			top: 0;
			bottom: 0;
			left: 0;
			right: 0;
			background: rgba(254, 126, 126, 0.7);
			transition: all 0.4s;
			visibility: hidden;
			opacity: 0;
		}
		.content {
			position: absolute;
			background: white;
			width: 400px;
			padding: 1em 2em;
			border-radius: 4px;
		}
		.modal:target {
			visibility: visible;
			opacity: 1;
		}
		.box-close {
			position: absolute;
			top: 0;
			right: 15px;
			color: #fe0606;
			text-decoration: none;
			font-size: 30px;
		}
	</style>

    <script>
          var $select1 = $( '#select1' ),
		$select2 = $( '#select2' ),
        $options = $select2.find( 'option' );

         $select1.on( 'change', function() {
	     $select2.html( $options.filter( '[value="' + this.value + '"]' ) );
          } ).trigger( 'change' );
    </script>
	<meta charset="utf-8">
	<title>Form</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Font-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/opensans-font.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/line-awesome/css/line-awesome.min.css' %}">
	<!-- Jquery -->
	<link rel="stylesheet" href="{% static 'https://jqueryvalidation.org/files/demo/site-demos.css' %}">
	<!-- Main Style Css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body class="form-v7">
	<div class="page-content">
		<div class="form-v7-content">
			<div class="form-left">
<!--				<img src="{% static 'images/form-v7.jpg' %}" alt="form">-->
				<p class="text-1"></p>
				<p class="text-2"></p>
			</div>
			<form class="form-detail" action="#" method="post" id="myform">

				<form class="login100-form validate-form" method="post">
					{% csrf_token %}
                        <input type="text" name="name" placeholder=" name" required><br>
    <input type="date" name="dob" placeholder="date of birth"><br>
    <input type="text" name="age" placeholder="age"><br>



      <legend>Choose your gender:</legend>
        <label for="male">Male</label>
        <input type="radio" name="gender" id="male" value="male" checked>
        <label for="female">Female</label>
        <input type="radio" name="gender" id="female" value="female"><br>


    <input type="text" name="phone" placeholder=" phone no"><br>
    <input type="text" name="mail id" placeholder="mail id"><br>
    <input type="text" name="address" placeholder="address"><br>

        <label for="cars">department:</label>
    <select class="form-control" name="select1" id="select1">

    <option value="1">commerce</option>
    <option value="2">bio maths</option>
    <option value="3">humanities</option>
    <option value="4">computer science</option>
    </select>
                    <label for="cars">course:</label>
    <select class="form-control" name="select2" id="select2">
    <option value="1">bba</option>
    <option value="1">bca</option>
    <option value="1">bcom</option>
    <option value="2">botany</option>
    <option value="2">zoology</option>
    <option value="2">science</option>
    <option value="3">ba</option>
    <option value="3">ma</option>
    <option value="4">computer science<option>

    </select>

    <label for="cars">purpose:</label>
    <select id="cars" name="cars">
    <option value="volvo">enquiry</option>
    <option value="saab">place order</option>
    <option value="fiat">return</option>

    </select><br>

    materials provide: <br>
              <input type="checkbox" id="C" name="C" value="C"/>
                 <label>debit note book</label> <br>
              <input type="checkbox" id="Java" name="Java" value="Java" checked=?yes?/>
                 <label>pen</label> <br>
              <input type="checkbox" id="Python" name="Python" value="Python"/>
                 <label>exam papers</label> <br>
















                    <input type="submit">
                    



				</form>

                {% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert" href="#">
      ×
      </button>
      <strong>{{message}}</strong><br>
        <a href="{% url 'schoolapp:home' %}">home</a>
    </div>
 {% endfor %}
{% endif %}






	<script src="{% static 'https://code.jquery.com/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js' %}"></script>
	<script src="{% static 'https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js' %}"></script>
	<script>

		jQuery.validator.setDefaults({
		  	debug: true,
		  	success:  function(label){
        		label.attr('id', 'valid');
   		 	},
		});
		$( "#myform" ).validate({
		  	rules: {
			    your_email: {
			      	required: true,
			      	email: true
			    },
			    password: "required",
		    	comfirm_password: {
		      		equalTo: "#password"
		    	}
		  	},
		  	messages: {
		  		username: {
		  			required: "Please enter an username"
		  		},
		  		your_email: {
		  			required: "Please provide an email"
		  		},
		  		password: {
	  				required: "Please provide a password"
		  		},
		  		comfirm_password: {
		  			required: "Please provide a password",
		      		equalTo: "Wrong Password"
		    	}
		  	}
		});
	</script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

schoolproject/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
haiii
</body>
</html>

schoolproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method="post">
					{% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user icon" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" href="" value="login">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">

						</span>
						<a class="txt2" href="{% url 'schoolapp:register' %}">
							Register
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="#">
							<i class="" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

schoolproject/templates/register.html
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>Form</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Font-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/opensans-font.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/line-awesome/css/line-awesome.min.css' %}">
	<!-- Jquery -->
	<link rel="stylesheet" href="{% static 'https://jqueryvalidation.org/files/demo/site-demos.css' %}">
	<!-- Main Style Css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body class="form-v7">
	<div class="page-content">
		<div class="form-v7-content">
			<div class="form-left">
<!--				<img src="{% static 'images/form-v7.jpg' %}" alt="form">-->
				<p class="text-1"></p>
				<p class="text-2"></p>
			</div>
			<form class="form-detail" action="#" method="post" id="myform">
				 {% csrf_token %}
				<div class="form-row">
					<label for="username">USERNAME</label>
					<input type="text" name="username" id="username" class="input-text">
				</div>
<!--				<div class="form-row">-->
<!--					<label for="your_email">E-MAIL</label>-->
<!--					<input type="text" name="your_email" id="your_email" class="input-text" required pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}">-->
<!--				</div>-->
				<div class="form-row">
					<label for="password">PASSWORD</label>
					<input type="password" name="password" id="password" class="input-text" required>
				</div>
				<div class="form-row">
					<label for="comfirm_password">CONFIRM PASSWORD</label>
					<input type="password" name="password1" id="comfirm_password" class="input-text" required>
				</div>
				<div class="form-row-last">
					<input type="submit" name="register" class="register"   value="Register">
<!--					<p><a href="{% url 'schoolapp:login' %}"></a></p>-->
				</div>
			</form>
		</div>
	</div>
	<script src="{% static 'https://code.jquery.com/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js' %}"></script>
	<script src="{% static 'https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js' %}"></script>
	<script>

		jQuery.validator.setDefaults({
		  	debug: true,
		  	success:  function(label){
        		label.attr('id', 'valid');
   		 	},
		});
		$( "#myform" ).validate({
		  	rules: {
			    your_email: {
			      	required: true,
			      	email: true
			    },
			    password: "required",
		    	comfirm_password: {
		      		equalTo: "#password"
		    	}
		  	},
		  	messages: {
		  		username: {
		  			required: "Please enter an username"
		  		},
		  		your_email: {
		  			required: "Please provide an email"
		  		},
		  		password: {
	  				required: "Please provide a password"
		  		},
		  		comfirm_password: {
		  			required: "Please provide a password",
		      		equalTo: "Wrong Password"
		    	}
		  	}
		});
	</script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>